version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: junco-umbrel_web_1
      APP_PORT: 8080

  web:
    image: localhost:5555/junco-umbrel-web:dev
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - adapter
      - server

  adapter:
    image: localhost:5555/junco-umbrel-adapter:dev
    restart: on-failure
    stop_grace_period: 1m
    environment:
      JUNCO_PORT: 8081
      JUNCO_NETWORK: mainnet
      JUNCO_DATA: /data
    volumes:
      - ${APP_DATA_DIR}/adapter:/data
    depends_on:
      - server

  server:
    image: localhost:5555/junco-umbrel-server:dev
    restart: on-failure
    stop_grace_period: 1m
    tty: true
    stdin_open: true
    volumes:
      - ${APP_DATA_DIR}/server:/data
