version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: junco-umbrel_web_1
      APP_PORT: 8080

  web:
    image: ghcr.io/aorobator/junco-umbrel-web:0.1.0
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 8080
      SPARROW_SERVER_URL: http://server:18080
    depends_on:
      - server

  server:
    image: ghcr.io/aorobator/junco-umbrel-server:0.1.0
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/server:/data
